# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "genomer-plugin-view"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Barton"]
  s.date = "2011-11-30"
  s.description = "TODO: longer description of your gem"
  s.email = "mail@michaelbarton.me.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/genomer-plugin-view.rb",
    "spec/genomer-plugin-view_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/michaelbarton/genomer-plugin-view"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<scaffolder>, ["~> 0.4.0"])
      s.add_runtime_dependency(%q<genomer>, ["~> 0.1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5"])
      s.add_development_dependency(%q<rspec>, ["~> 2.7.0"])
      s.add_development_dependency(%q<scaffolder-test-helpers>, ["~> 0.4.0"])
      s.add_development_dependency(%q<cucumber>, ["~> 1.0.4"])
      s.add_development_dependency(%q<aruba>, ["~> 0.4.6"])
    else
      s.add_dependency(%q<scaffolder>, ["~> 0.4.0"])
      s.add_dependency(%q<genomer>, ["~> 0.1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5"])
      s.add_dependency(%q<rspec>, ["~> 2.7.0"])
      s.add_dependency(%q<scaffolder-test-helpers>, ["~> 0.4.0"])
      s.add_dependency(%q<cucumber>, ["~> 1.0.4"])
      s.add_dependency(%q<aruba>, ["~> 0.4.6"])
    end
  else
    s.add_dependency(%q<scaffolder>, ["~> 0.4.0"])
    s.add_dependency(%q<genomer>, ["~> 0.1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5"])
    s.add_dependency(%q<rspec>, ["~> 2.7.0"])
    s.add_dependency(%q<scaffolder-test-helpers>, ["~> 0.4.0"])
    s.add_dependency(%q<cucumber>, ["~> 1.0.4"])
    s.add_dependency(%q<aruba>, ["~> 0.4.6"])
  end
end

